import { SupplierType } from '@prisma/client';

export type ServiceSeed = {
  index: number;
  name: string;
  district: string;
  address: string;
  city: string;
  phone: string;
  email: string;
  uniqueCode: string;
  bulstat: string;
  vatNumber: string;
  description: string;
};

export type MechanicSeed = {
  index: number;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  specialization: string;
  skills: string;
  primaryService: number;
  memberships: number[];
};

export type PendingPersonSeed = {
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  targetService: number;
};

export type RepairTemplate = {
  title: string;
  description: string;
  diagnosis: string;
  supplierType: SupplierType;
  labor: { name: string; quantity: number; unitPrice: number };
  parts: Array<{ name: string; quantity: number; unitPrice: number }>;
  consumables: Array<{ name: string; quantity: number; unitPrice: number }>;
};

export const serviceSeeds: ServiceSeed[] = [
  {
    index: 1,
    name: 'Трак Кар Сървиз Център',
    district: 'Център',
    address: 'бул. Освобождение 97',
    city: 'Пловдив',
    phone: '+359 32 910 1001',
    email: 'trackcar.center@automanager.bg',
    uniqueCode: 'PLD101',
    bulstat: '208100101',
    vatNumber: 'BG208100101',
    description: 'Многопрофилен сервиз за диагностика, двигатели и спирачни системи.',
  },
  {
    index: 2,
    name: 'Авто Хъб Кършияка',
    district: 'Кършияка',
    address: 'бул. Дунав 5',
    city: 'Пловдив',
    phone: '+359 32 910 1002',
    email: 'autohub.karshiyaka@automanager.bg',
    uniqueCode: 'PLD202',
    bulstat: '208100202',
    vatNumber: 'BG208100202',
    description: 'Сервиз с фокус върху дизелови системи, трансмисии и обслужване.',
  },
  {
    index: 3,
    name: 'Марица Драйв Сервиз',
    district: 'Тракия',
    address: 'бул. Шести септември 221',
    city: 'Пловдив',
    phone: '+359 32 910 1003',
    email: 'maritsa.drive@automanager.bg',
    uniqueCode: 'PLD303',
    bulstat: '208100303',
    vatNumber: 'BG208100303',
    description: 'Сервизен център за окачване, гуми, климатизация и автоелектроника.',
  },
];

export const mechanicSeeds: MechanicSeed[] = [
  {
    index: 1,
    firstName: 'Михаил',
    lastName: 'Костов',
    email: 'mechanic1@automanager.bg',
    phone: '+359 88 100 0001',
    specialization: 'Двигатели',
    skills: 'Ангренажни системи, компресия, диагностика',
    primaryService: 1,
    memberships: [1],
  },
  {
    index: 2,
    firstName: 'Георги',
    lastName: 'Стоев',
    email: 'mechanic2@automanager.bg',
    phone: '+359 88 100 0002',
    specialization: 'Спирачки и ходова част',
    skills: 'Дискове и накладки, лагери, реглаж',
    primaryService: 1,
    memberships: [1, 2],
  },
  {
    index: 3,
    firstName: 'Пламен',
    lastName: 'Йорданов',
    email: 'mechanic3@automanager.bg',
    phone: '+359 88 100 0003',
    specialization: 'Автоелектроника',
    skills: 'Стартери, алтернатори, CAN диагностика',
    primaryService: 1,
    memberships: [1],
  },
  {
    index: 4,
    firstName: 'Христо',
    lastName: 'Велев',
    email: 'mechanic4@automanager.bg',
    phone: '+359 88 100 0004',
    specialization: 'Трансмисии',
    skills: 'Съединители, маховици, обслужване на кутии',
    primaryService: 2,
    memberships: [2],
  },
  {
    index: 5,
    firstName: 'Николай',
    lastName: 'Тодоров',
    email: 'mechanic5@automanager.bg',
    phone: '+359 88 100 0005',
    specialization: 'Дизелови системи',
    skills: 'DPF, EGR, дюзи и горивна система',
    primaryService: 2,
    memberships: [2, 3],
  },
  {
    index: 6,
    firstName: 'Васил',
    lastName: 'Петров',
    email: 'mechanic6@automanager.bg',
    phone: '+359 88 100 0006',
    specialization: 'Климатични системи',
    skills: 'Компресори, кондензатори, вакуумиране',
    primaryService: 3,
    memberships: [3],
  },
  {
    index: 7,
    firstName: 'Даниел',
    lastName: 'Радев',
    email: 'mechanic7@automanager.bg',
    phone: '+359 88 100 0007',
    specialization: 'Диагностика',
    skills: 'Ламбда сонди, адаптации, диагностика в реално време',
    primaryService: 3,
    memberships: [3, 1],
  },
  {
    index: 8,
    firstName: 'Иван',
    lastName: 'Григоров',
    email: 'mechanic8@automanager.bg',
    phone: '+359 88 100 0008',
    specialization: 'Окачване и гуми',
    skills: 'Амортисьори, носачи, монтаж и баланс',
    primaryService: 3,
    memberships: [3],
  },
];

export const pendingMechanics: PendingPersonSeed[] = [
  {
    firstName: 'Стефан',
    lastName: 'Илиев',
    email: 'pending.mechanic1@automanager.bg',
    phone: '+359 88 700 0001',
    targetService: 1,
  },
  {
    firstName: 'Александър',
    lastName: 'Колев',
    email: 'pending.mechanic2@automanager.bg',
    phone: '+359 88 700 0002',
    targetService: 2,
  },
  {
    firstName: 'Борис',
    lastName: 'Лазаров',
    email: 'pending.mechanic3@automanager.bg',
    phone: '+359 88 700 0003',
    targetService: 3,
  },
];

export const pendingClients: PendingPersonSeed[] = [
  {
    firstName: 'Елица',
    lastName: 'Стоянова',
    email: 'pending.client1@automanager.bg',
    phone: '+359 88 800 0001',
    targetService: 1,
  },
  {
    firstName: 'Марин',
    lastName: 'Георгиев',
    email: 'pending.client2@automanager.bg',
    phone: '+359 88 800 0002',
    targetService: 2,
  },
  {
    firstName: 'Надежда',
    lastName: 'Павлова',
    email: 'pending.client3@automanager.bg',
    phone: '+359 88 800 0003',
    targetService: 3,
  },
];

export const clientFirstNames = [
  'Антон',
  'Мария',
  'Петър',
  'Ралица',
  'Христо',
  'Вероника',
  'Йордан',
  'Кристина',
  'Калин',
  'Силвия',
  'Илия',
  'Теодора',
  'Радослав',
  'Габриела',
  'Тодор',
  'Михаела',
  'Симеон',
  'Виктория',
  'Даниел',
  'Елена',
  'Станислав',
  'Никола',
  'Яна',
  'Боряна',
  'Деян',
  'Любомир',
  'Цветелина',
  'Атанас',
  'Мартин',
  'Николета',
];

export const clientLastNames = [
  'Ангелов',
  'Георгиева',
  'Димитров',
  'Захариева',
  'Желязков',
  'Тонева',
  'Николов',
  'Милева',
  'Лазаров',
  'Радева',
  'Павлов',
  'Узунова',
  'Стефанов',
  'Филипова',
  'Караиванов',
  'Борисова',
  'Орлински',
  'Евтимова',
  'Иванов',
  'Пенева',
  'Маринов',
  'Хаджиев',
  'Кирова',
  'Вълчева',
  'Кънчев',
  'Трифонов',
  'Митева',
  'Попов',
  'Костадинов',
  'Славова',
];

export const vehicleBrands = [
  'VW',
  'Audi',
  'BMW',
  'Mercedes',
  'Skoda',
  'Toyota',
  'Ford',
  'Opel',
  'Renault',
  'Peugeot',
  'Nissan',
  'Honda',
  'Mazda',
  'Hyundai',
  'Kia',
];

export const vehicleModels = [
  'Golf 7',
  'Passat B8',
  'Tiguan II',
  'Touran II',
  'A3 8V',
  'A4 B9',
  'A6 C7',
  'Q5 FY',
  '320d G20',
  'X3 G01',
  '520d G30',
  'X5 G05',
  'C 220 W205',
  'GLC 220d',
  'E 220 W213',
  'GLA 200',
  'Octavia III',
  'Superb III',
  'Kodiaq',
  'Fabia III',
  'Corolla',
  'RAV4',
  'Yaris',
  'Avensis',
  'Focus',
  'Mondeo',
  'Kuga',
  'Fiesta',
  'Astra K',
  'Insignia B',
  'Mokka',
  'Corsa E',
  'Megane IV',
  'Kadjar',
  'Clio IV',
  'Captur',
  '308',
  '3008',
  '208',
  '508',
  'Qashqai',
  'X-Trail',
  'Micra',
  'Juke',
  'Civic',
  'CR-V',
  'Jazz',
  'Accord',
  'Mazda 3',
  'CX-5',
  'Mazda 6',
  'Mazda 2',
  'i30',
  'Tucson',
  'i20',
  'Elantra',
  'Ceed',
  'Sportage',
  'Rio',
  'Optima',
  'Duster',
  'Logan',
  'S60',
  'XC60',
];

export const repairTemplates: RepairTemplate[] = [
  {
    title: 'Годишно обслужване',
    description: 'Смяна на масло, филтри и базов преглед на ходова част.',
    diagnosis: 'Маслото е с изчерпан ресурс, филтрите са замърсени над допустимото.',
    supplierType: SupplierType.CONSUMABLES,
    labor: { name: 'Труд: годишно обслужване', quantity: 1, unitPrice: 45 },
    parts: [
      { name: 'Маслен филтър', quantity: 1, unitPrice: 18 },
      { name: 'Въздушен филтър', quantity: 1, unitPrice: 24 },
      { name: 'Горивен филтър', quantity: 1, unitPrice: 34 },
      { name: 'Филтър купе', quantity: 1, unitPrice: 22 },
    ],
    consumables: [{ name: 'Двигателно масло 5W-30 (5L)', quantity: 1, unitPrice: 62 }],
  },
  {
    title: 'Смяна предни дискове и накладки',
    description: 'Подмяна на предни спирачни дискове и комплект накладки.',
    diagnosis: 'Установен е ръб по дисковете и неравномерно износване на накладките.',
    supplierType: SupplierType.PARTS,
    labor: { name: 'Труд: предна спирачна система', quantity: 2, unitPrice: 40 },
    parts: [
      { name: 'Предни дискове', quantity: 2, unitPrice: 92 },
      { name: 'Предни накладки', quantity: 1, unitPrice: 86 },
    ],
    consumables: [{ name: 'Спирачна течност DOT4 (1L)', quantity: 1, unitPrice: 14 }],
  },
  {
    title: 'Смяна задни накладки и обслужване апарати',
    description: 'Смяна на задни накладки и ревизия на водачи и бутала.',
    diagnosis: 'Задните апарати са със затруднено движение, накладките са под сервизен минимум.',
    supplierType: SupplierType.PARTS,
    labor: { name: 'Труд: задна спирачна система', quantity: 2, unitPrice: 39 },
    parts: [
      { name: 'Задни накладки', quantity: 1, unitPrice: 74 },
      { name: 'Ремонтен комплект водачи заден апарат', quantity: 1, unitPrice: 29 },
    ],
    consumables: [
      { name: 'Спирачна грес за водачи', quantity: 1, unitPrice: 8 },
      { name: 'Спрей за спирачки', quantity: 1, unitPrice: 6 },
    ],
  },
  {
    title: 'Смяна ангренажен комплект',
    description: 'Смяна на ангренажен комплект, водна помпа и пистов ремък.',
    diagnosis: 'Налице са микропукнатини по ремъка и луфт в лагера на водната помпа.',
    supplierType: SupplierType.PARTS,
    labor: { name: 'Труд: ангренажен комплект', quantity: 5, unitPrice: 46 },
    parts: [
      { name: 'Ангренажен комплект', quantity: 1, unitPrice: 265 },
      { name: 'Водна помпа', quantity: 1, unitPrice: 126 },
      { name: 'Пистов ремък', quantity: 1, unitPrice: 39 },
    ],
    consumables: [{ name: 'Антифриз G12+ (1.5L)', quantity: 3, unitPrice: 13 }],
  },
  {
    title: 'Смяна ангренажна верига',
    description: 'Подмяна на комплект верига, обтегач и водачи.',
    diagnosis: 'При студен старт се чува метален шум, установено е удължаване на веригата.',
    supplierType: SupplierType.PARTS,
    labor: { name: 'Труд: ангренажна верига', quantity: 7, unitPrice: 52 },
    parts: [
      { name: 'Комплект ангренажна верига', quantity: 1, unitPrice: 420 },
      { name: 'Маслена помпа верига', quantity: 1, unitPrice: 74 },
      { name: 'Семеринг колянов вал', quantity: 1, unitPrice: 18 },
    ],
    consumables: [{ name: 'Двигателно масло 5W-30 (5L)', quantity: 1, unitPrice: 62 }],
  },
  {
    title: 'Смяна съединител и маховик',
    description: 'Ремонт на съединител с комплект и двумасов маховик.',
    diagnosis: 'Налице е приплъзване при натоварване и вибрации от маховика.',
    supplierType: SupplierType.PARTS,
    labor: { name: 'Труд: съединител и маховик', quantity: 6, unitPrice: 48 },
    parts: [
      { name: 'Комплект съединител', quantity: 1, unitPrice: 348 },
      { name: 'Двумасов маховик', quantity: 1, unitPrice: 512 },
    ],
    consumables: [{ name: 'Трансмисионно масло 75W-80 (1L)', quantity: 2, unitPrice: 16 }],
  },
  {
    title: 'Обслужване автоматична кутия',
    description: 'Смяна масло и филтър на автоматична трансмисия.',
    diagnosis: 'Има забавяне при превключване и потъмняло трансмисионно масло.',
    supplierType: SupplierType.CONSUMABLES,
    labor: { name: 'Труд: обслужване автоматична кутия', quantity: 2, unitPrice: 58 },
    parts: [{ name: 'Филтър автоматична скоростна кутия', quantity: 1, unitPrice: 78 }],
    consumables: [{ name: 'ATF масло (1L)', quantity: 7, unitPrice: 19 }],
  },
  {
    title: 'Ремонт климатична система',
    description: 'Смяна на компресор и дехидратор, вакуумиране и зареждане.',
    diagnosis: 'Компресорът не създава работно налягане, в системата има влага.',
    supplierType: SupplierType.CONSUMABLES,
    labor: { name: 'Труд: климатична система', quantity: 3, unitPrice: 45 },
    parts: [
      { name: 'Компресор климатик', quantity: 1, unitPrice: 448 },
      { name: 'Филтър-дехидратор', quantity: 1, unitPrice: 74 },
    ],
    consumables: [{ name: 'Фреон R134a (грам)', quantity: 650, unitPrice: 0.12 }],
  },
  {
    title: 'Сервиз на климатик и откриване теч',
    description: 'Тест с UV добавка, вакуумиране и дозареждане.',
    diagnosis: 'Ниско налягане в ниската линия и следи от теч по кондензатора.',
    supplierType: SupplierType.SERVICES,
    labor: { name: 'Труд: диагностика и сервиз климатик', quantity: 2, unitPrice: 41 },
    parts: [{ name: 'О-пръстени климатична система (комплект)', quantity: 1, unitPrice: 18 }],
    consumables: [
      { name: 'UV добавка за климатик', quantity: 1, unitPrice: 12 },
      { name: 'Фреон R134a (грам)', quantity: 420, unitPrice: 0.12 },
    ],
  },
  {
    title: 'Смяна термостат и промивка охлаждане',
    description: 'Подмяна на термостат, промивка и пълнене с нов антифриз.',
    diagnosis: 'Двигателят загрява бавно и поддържа нестабилна работна температура.',
    supplierType: SupplierType.PARTS,
    labor: { name: 'Труд: охладителна система', quantity: 2, unitPrice: 39 },
    parts: [{ name: 'Термостат комплект', quantity: 1, unitPrice: 96 }],
    consumables: [
      { name: 'Антифриз G12+ (1.5L)', quantity: 4, unitPrice: 13 },
      { name: 'Препарат за промивка охладителна система', quantity: 1, unitPrice: 14 },
    ],
  },
  {
    title: 'Смяна радиатор и маркучи',
    description: 'Подмяна на основен радиатор и комплект горни/долни маркучи.',
    diagnosis: 'Има теч по радиатора и омекнали маркучи с микропукнатини.',
    supplierType: SupplierType.PARTS,
    labor: { name: 'Труд: радиатор и маркучи', quantity: 3, unitPrice: 42 },
    parts: [
      { name: 'Радиатор охлаждане', quantity: 1, unitPrice: 188 },
      { name: 'Горен маркуч радиатор', quantity: 1, unitPrice: 28 },
      { name: 'Долен маркуч радиатор', quantity: 1, unitPrice: 26 },
    ],
    consumables: [{ name: 'Антифриз G12+ (1.5L)', quantity: 4, unitPrice: 13 }],
  },
  {
    title: 'Смяна амортисьори и тампони отпред',
    description: 'Комплектна подмяна на предни амортисьори, тампони и лагери.',
    diagnosis: 'При тест се отчита слабо демпфиране и шум от горни тампони.',
    supplierType: SupplierType.PARTS,
    labor: { name: 'Труд: предно окачване', quantity: 3, unitPrice: 40 },
    parts: [
      { name: 'Предни амортисьори', quantity: 2, unitPrice: 128 },
      { name: 'Горни тампони амортисьори', quantity: 2, unitPrice: 32 },
      { name: 'Лагери макферсон', quantity: 2, unitPrice: 24 },
    ],
    consumables: [{ name: 'Спрей проникващ (400 ml)', quantity: 1, unitPrice: 9 }],
  },
  {
    title: 'Смяна носачи и биалети',
    description: 'Подмяна на долни предни носачи и комплект биалети.',
    diagnosis: 'Има луфт в шарнирите и тракане при преминаване през неравности.',
    supplierType: SupplierType.PARTS,
    labor: { name: 'Труд: носачи и биалети', quantity: 3, unitPrice: 41 },
    parts: [
      { name: 'Предни долни носачи', quantity: 2, unitPrice: 145 },
      { name: 'Биалети комплект', quantity: 1, unitPrice: 48 },
    ],
    consumables: [{ name: 'Болтове за окачване (комплект)', quantity: 1, unitPrice: 18 }],
  },
  {
    title: 'Смяна лагер главина',
    description: 'Подмяна на лагер главина и проверка на геометрията.',
    diagnosis: 'Налице е шум тип бучене, който се засилва при завой.',
    supplierType: SupplierType.PARTS,
    labor: { name: 'Труд: лагер главина', quantity: 2, unitPrice: 39 },
    parts: [{ name: 'Лагер главина преден', quantity: 1, unitPrice: 92 }],
    consumables: [{ name: 'Грес за лагерни възли', quantity: 1, unitPrice: 11 }],
  },
  {
    title: 'Смяна накрайници и реглаж преден мост',
    description: 'Подмяна на външни накрайници и реглаж на преден мост.',
    diagnosis: 'Установени са луфтове в кормилните накрайници и отклонение в сходимостта.',
    supplierType: SupplierType.SERVICES,
    labor: { name: 'Труд: кормилна система и реглаж', quantity: 2, unitPrice: 42 },
    parts: [
      { name: 'Външен кормилен накрайник', quantity: 2, unitPrice: 34 },
      { name: 'Контрагайки накрайник', quantity: 2, unitPrice: 5 },
    ],
    consumables: [{ name: 'Услуга: 3D реглаж преден мост', quantity: 1, unitPrice: 38 }],
  },
  {
    title: 'Смяна алтернатор',
    description: 'Подмяна на алтернатор и проверка на зарядна система.',
    diagnosis: 'Зарядното напрежение е под норма, установено е износване на диоден блок.',
    supplierType: SupplierType.PARTS,
    labor: { name: 'Труд: алтернатор', quantity: 2, unitPrice: 40 },
    parts: [{ name: 'Алтернатор 140A', quantity: 1, unitPrice: 285 }],
    consumables: [{ name: 'Пистов ремък', quantity: 1, unitPrice: 39 }],
  },
  {
    title: 'Ремонт стартер',
    description: 'Рециклиране на стартер с нов бендикс и втулки.',
    diagnosis: 'Стартерът превърта и има забавено завъртане при топъл двигател.',
    supplierType: SupplierType.SERVICES,
    labor: { name: 'Труд: демонтаж/монтаж и рециклиране стартер', quantity: 2, unitPrice: 44 },
    parts: [
      { name: 'Бендикс стартер', quantity: 1, unitPrice: 58 },
      { name: 'Втулки стартер (комплект)', quantity: 1, unitPrice: 12 },
    ],
    consumables: [{ name: 'Смазка за механизъм стартер', quantity: 1, unitPrice: 7 }],
  },
  {
    title: 'Смяна акумулатор и адаптация',
    description: 'Подмяна на акумулатор и обучение на енергиен мениджмънт.',
    diagnosis: 'Пусковият ток е под минималните стойности, отчетен е висок вътрешен пад.',
    supplierType: SupplierType.CONSUMABLES,
    labor: { name: 'Труд: акумулатор и адаптация', quantity: 1, unitPrice: 28 },
    parts: [{ name: 'Акумулатор AGM 70Ah', quantity: 1, unitPrice: 218 }],
    consumables: [{ name: 'Антикорозионен спрей за клеми', quantity: 1, unitPrice: 6 }],
  },
  {
    title: 'Ремонт горивна система',
    description: 'Смяна горивен филтър и уплътнения на дюзи.',
    diagnosis: 'Има трудно палене и корекции на дюзите извън референтния диапазон.',
    supplierType: SupplierType.PARTS,
    labor: { name: 'Труд: горивна система', quantity: 3, unitPrice: 46 },
    parts: [
      { name: 'Горивен филтър', quantity: 1, unitPrice: 34 },
      { name: 'Уплътнения дюзи (комплект)', quantity: 1, unitPrice: 22 },
      { name: 'Обратни маркучи дюзи', quantity: 1, unitPrice: 17 },
    ],
    consumables: [{ name: 'Почистваща добавка за дизел', quantity: 1, unitPrice: 14 }],
  },
  {
    title: 'Смяна EGR клапан',
    description: 'Подмяна на EGR клапан и адаптация след монтаж.',
    diagnosis: 'Клапанът блокира в отворено положение и предизвиква нестабилен празен ход.',
    supplierType: SupplierType.PARTS,
    labor: { name: 'Труд: EGR система', quantity: 2, unitPrice: 43 },
    parts: [{ name: 'EGR клапан', quantity: 1, unitPrice: 246 }],
    consumables: [{ name: 'Гарнитура EGR клапан', quantity: 1, unitPrice: 12 }],
  },
  {
    title: 'Почистване DPF и принудителна регенерация',
    description: 'Почистване на DPF, диагностика и принудителна регенерация.',
    diagnosis: 'Саждите в DPF са над критичния праг и автомобилът преминава в авариен режим.',
    supplierType: SupplierType.SERVICES,
    labor: { name: 'Труд: DPF диагностика и регенерация', quantity: 3, unitPrice: 45 },
    parts: [{ name: 'Датчик диференциално налягане DPF', quantity: 1, unitPrice: 89 }],
    consumables: [{ name: 'Препарат за DPF почистване', quantity: 1, unitPrice: 36 }],
  },
  {
    title: 'Смяна запалителни бобини и свещи',
    description: 'Подмяна на комплект бобини и свещи при прекъсване на цилиндър.',
    diagnosis: 'Диагностиката отчита пропуски в запалването и високо съпротивление на бобина.',
    supplierType: SupplierType.PARTS,
    labor: { name: 'Труд: запалителна система', quantity: 1, unitPrice: 32 },
    parts: [
      { name: 'Запалителни бобини', quantity: 4, unitPrice: 42 },
      { name: 'Запалителни свещи', quantity: 4, unitPrice: 14 },
    ],
    consumables: [{ name: 'Диелектрична грес за бобини', quantity: 1, unitPrice: 6 }],
  },
  {
    title: 'Смяна комплект гуми и баланс',
    description: 'Смяна на комплект гуми с баланс и нови вентили.',
    diagnosis: 'Старите гуми са с неравномерно износване и ниска остатъчна дълбочина на грайфера.',
    supplierType: SupplierType.TIRES,
    labor: { name: 'Труд: монтаж и баланс', quantity: 1, unitPrice: 39 },
    parts: [{ name: 'Гуми 205/55R16', quantity: 4, unitPrice: 108 }],
    consumables: [{ name: 'Вентили комплект', quantity: 1, unitPrice: 12 }],
  },
  {
    title: 'Смяна турбо маркуч и интеркулер скоби',
    description: 'Отстраняване на теч по пътя на нагнетения въздух.',
    diagnosis: 'При натоварване има пад на налягане и омасляване около турбо маркуча.',
    supplierType: SupplierType.PARTS,
    labor: { name: 'Труд: турбо пътища', quantity: 2, unitPrice: 40 },
    parts: [
      { name: 'Маркуч турбо - интеркулер', quantity: 1, unitPrice: 84 },
      { name: 'Скоби интеркулер (комплект)', quantity: 1, unitPrice: 16 },
    ],
    consumables: [{ name: 'Почистващ препарат за всмукателен тракт', quantity: 1, unitPrice: 11 }],
  },
  {
    title: 'Смяна масло и филтър Haldex',
    description: 'Обслужване на Haldex съединител с нов филтър и масло.',
    diagnosis: 'При потегляне има забавено включване на задния мост.',
    supplierType: SupplierType.CONSUMABLES,
    labor: { name: 'Труд: обслужване Haldex', quantity: 2, unitPrice: 44 },
    parts: [{ name: 'Филтър Haldex', quantity: 1, unitPrice: 48 }],
    consumables: [{ name: 'Масло Haldex (1L)', quantity: 1, unitPrice: 36 }],
  },
];
